services:
  - type: web
    name: authigniter
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false
      - key: THIRD_PARTY_API
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: DID_API
        sync: false
      - key: DID_AUTHORITY
        sync: false
      - key: DID_TOKEN
        sync: false
      - key: DID_MANIFEST
        sync: false
